import Fastify from 'fastify'; import cors from '@fastify/cors'; import helmet from '@fastify/helmet'; import rateLimit from '@fastify/rate-limit';
import { z } from 'zod'; import { cached } from './cache.js'; import { careers,honors,news,people as mockPeople,statistics,timeline } from './mock.js'; import { queryPeople } from './notion.js';
const querySchema=z.object({page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20),category:z.string().optional(),nationality:z.string().optional(),keyword:z.string().max(100).optional(),featured:z.enum(['true','false']).optional()});
export async function buildApp(){const app=Fastify({logger:{level:process.env.LOG_LEVEL??'info'},bodyLimit:64*1024});
 await app.register(helmet); await app.register(cors,{origin:(origin,cb)=>{const allowed=(process.env.ALLOWED_ORIGINS??'http://localhost:4321').split(',');cb(null,!origin||allowed.includes(origin))}}); await app.register(rateLimit,{max:100,timeWindow:'1 minute'});
 const ttl=Number(process.env.CACHE_TTL_SECONDS??300)*1000; const getPeople=async()=>cached('people:v1',ttl,()=>process.env.USE_MOCK_DATA!=='false'?Promise.resolve(mockPeople):queryPeople());
 app.get('/health',async()=>({status:'ok',timestamp:new Date().toISOString()})); app.get('/api/v1/config',async()=>({success:true,data:{mock:process.env.USE_MOCK_DATA!=='false',notionVersion:process.env.NOTION_VERSION??'2025-09-03'},meta:{cached:false}}));
 app.get('/api/v1/people',async(req,reply)=>{const q=querySchema.safeParse(req.query);if(!q.success)return reply.code(400).send({success:false,data:null,error:{code:'INVALID_QUERY',message:'查询参数无效'}});const hit=await getPeople();let items=hit.value.filter(p=>(!q.data.category||p.category===q.data.category)&&(!q.data.nationality||p.nationality===q.data.nationality)&&(!q.data.featured||p.featured===(q.data.featured==='true')));if(q.data.keyword){const k=q.data.keyword.toLowerCase();items=items.filter(p=>[p.nameZh,p.nameEn,p.slug,p.nickname,p.nationality].some(v=>v.toLowerCase().includes(k)))}const total=items.length,start=(q.data.page-1)*q.data.pageSize;return {success:true,data:items.slice(start,start+q.data.pageSize),meta:{page:q.data.page,pageSize:q.data.pageSize,total,cached:hit.cached,stale:hit.stale}}});
 app.get('/api/v1/search',{config:{rateLimit:{max:30,timeWindow:'1 minute'}}},async(req,reply)=>{const q=z.object({keyword:z.string().min(1).max(100)}).safeParse(req.query);if(!q.success)return reply.code(400).send({success:false,data:null,error:{code:'INVALID_QUERY',message:'请输入搜索词'}});const all=(await getPeople()).value,k=q.data.keyword.toLowerCase();const score=(p:any)=>p.nameZh===q.data.keyword?0:p.nameEn.toLowerCase()===k?1:p.slug===k?2:p.nickname.includes(q.data.keyword)?3:p.nameZh.includes(q.data.keyword)?4:p.nameEn.toLowerCase().includes(k)?5:6;const data=all.filter(p=>score(p)<6||p.nationality.includes(q.data.keyword)||p.category===k).sort((a,b)=>score(a)-score(b));return {success:true,data,meta:{total:data.length,cached:true}}});
 app.get('/api/v1/people/:slug',async(req,reply)=>{const {slug}=req.params as any;const person=(await getPeople()).value.find(p=>p.slug===slug);return person?{success:true,data:person,meta:{cached:true}}:reply.code(404).send({success:false,data:null,error:{code:'NOT_FOUND',message:'未找到该人物'}})});
 for(const [path,data] of [['career',careers],['statistics',statistics],['honors',honors],['timeline',timeline]] as const) app.get(`/api/v1/people/:slug/${path}`,async req=>{const {slug}=req.params as any;return {success:true,data:data.filter((x:any)=>x.personSlug===slug),meta:{cached:true}}});
 app.get('/api/v1/people/:slug/news',async req=>{const {slug}=req.params as any;return {success:true,data:news.filter(x=>x.person===slug),meta:{cached:true}}}); app.get('/api/v1/news',async()=>({success:true,data:news,meta:{cached:true}})); app.get('/api/v1/news/latest',async()=>({success:true,data:news,meta:{cached:true}}));
 app.get('/api/v1/people/:slug/media',async()=>({success:true,data:[],meta:{cached:true}})); app.get('/api/v1/people/:slug/related',async()=>({success:true,data:[],meta:{cached:true}}));
 app.get('/api/v1/categories/:category',async(req)=>{const {category}=req.params as any;const all=(await getPeople()).value;const data=all.filter(p=>p.category===category);return {success:true,data,meta:{total:data.length,cached:true}}});
 app.setErrorHandler((e,req,reply)=>{req.log.error({err:e},'request failed');reply.code(502).send({success:false,data:null,error:{code:'UPSTREAM_REQUEST_FAILED',message:'人物数据暂时无法获取'}})}); return app; }
