import type { CareerRecord, Honor, NewsArticle, Person, Statistic, TimelineEvent } from '@legend/shared';

const base = (slug:string,nameZh:string,nameEn:string,category:Person['category'],nationality:string,status:Person['status']='active'):Person => ({ id:slug,slug,nameZh,nameEn,nickname:'',category,nationality,birthDate:'1980-01-01',birthPlace:'',summary:`${nameZh}是享誉世界的${category==='film'?'电影人':category==='music'?'音乐人':'运动员'}。`,biography:`${nameZh}以卓越的职业成就、持久影响力和独特风格成为时代代表人物。`,avatarUrl:`/images/people/${slug}/avatar.webp`,coverUrl:`/images/people/${slug}/cover.webp`,status,featured:true,keywords:[nameZh,nameEn],views:0 });
export const people:Person[] = [
  {...base('lionel-messi','梅西','Lionel Messi','football','阿根廷'),nickname:'莱奥',birthDate:'1987-06-24',birthPlace:'罗萨里奥',summary:'阿根廷足球运动员，世界杯冠军、八次金球奖得主，被广泛视为足球史上最杰出的球员之一。',biography:'梅西出生于阿根廷罗萨里奥，少年时期加入巴塞罗那青训体系。他以出色的盘带、组织和得分能力赢得众多俱乐部与个人荣誉，并于2022年带领阿根廷国家队夺得世界杯。'},
  base('cristiano-ronaldo','C罗','Cristiano Ronaldo','football','葡萄牙'), base('pele','贝利','Pelé','football','巴西','deceased'), base('diego-maradona','马拉多纳','Diego Maradona','football','阿根廷','deceased'), base('neymar','内马尔','Neymar','football','巴西'), base('kylian-mbappe','姆巴佩','Kylian Mbappé','football','法国'),
  base('michael-jordan','乔丹','Michael Jordan','basketball','美国','retired'), base('kobe-bryant','科比','Kobe Bryant','basketball','美国','deceased'), base('lebron-james','詹姆斯','LeBron James','basketball','美国'),
  base('stephen-chow','周星驰','Stephen Chow','film','中国香港'), base('jackie-chan','成龙','Jackie Chan','film','中国香港'), base('andy-lau','刘德华','Andy Lau','film','中国香港'), base('tony-leung','梁朝伟','Tony Leung','film','中国香港'),
  base('taylor-swift','泰勒·斯威夫特','Taylor Swift','music','美国'), base('michael-jackson','迈克尔·杰克逊','Michael Jackson','music','美国','deceased'), base('jay-chou','周杰伦','Jay Chou','music','中国台湾')
];
export const careers:CareerRecord[]=[{id:'messi-barca',personSlug:'lionel-messi',organization:'巴塞罗那',role:'前锋',startDate:'2004-10-16',endDate:'2021-06-30',appearances:778,goals:672,assists:303,description:'完成一线队首秀并成长为俱乐部历史代表人物。'},{id:'messi-argentina',personSlug:'lionel-messi',organization:'阿根廷国家队',role:'队长 / 前锋',startDate:'2005-08-17',appearances:180,goals:100,description:'率队赢得美洲杯和世界杯。'}];
export const statistics:Statistic[]=[{id:'messi-career',personSlug:'lionel-messi',season:'职业生涯',team:'俱乐部与国家队',competition:'全部',appearances:1000,goals:800,assists:350,extra:{note:'演示数据，接入 Notion 后以实际资料为准'}}];
export const honors:Honor[]=[{id:'world-cup-2022',personSlug:'lionel-messi',year:2022,category:'国家队',organization:'阿根廷',count:1,description:'FIFA 世界杯冠军',featured:true},{id:'ballon-dor',personSlug:'lionel-messi',year:2023,category:'个人',organization:'法国足球',count:8,description:'金球奖',featured:true}];
export const timeline:TimelineEvent[]=[{id:'birth',personSlug:'lionel-messi',eventDate:'1987-06-24',year:1987,eventType:'birth',title:'出生',description:'出生于阿根廷罗萨里奥。'},{id:'debut',personSlug:'lionel-messi',eventDate:'2004-10-16',year:2004,eventType:'career',title:'巴塞罗那一线队首秀',description:'正式开启职业生涯。'},{id:'world-cup',personSlug:'lionel-messi',eventDate:'2022-12-18',year:2022,eventType:'championship',title:'赢得世界杯',description:'带领阿根廷队夺得卡塔尔世界杯冠军。'}];
export const news:NewsArticle[]=[{id:'demo-1',title:'梅西人物档案示例内容',summary:'当前未配置真实新闻 API，本条内容用于展示新闻卡片和动态刷新能力。',source:'演示数据',sourceUrl:'https://example.com',publishedAt:'2026-01-01T00:00:00.000Z',imageUrl:'',person:'lionel-messi',isDemo:true,verified:false}];
